### ISSUE TITLE
rsync permissions issues on windows

### ISSUE THREAD

**Issue by andrewbt** [OpenTreeMap/otm-vagrant#12]
In my case, I ran into a number of "permission denied" issues with the rsync folders in cygwin. A similar case is described here: https://github.com/mitchellh/vagrant/issues/3256

The solution posted at that link, of adding the following to each rsync folder definition in the vagrant file, worked for me:

```:rsync__args => ["--chmod=ugo=rwX","--verbose", "--archive", "--delete", "-z"]```

Possible resolutions?

- add this to Vagrantfile (con: may not be necessary in all cases)
- add an alternative Vagrantfile
- put this in the readme and make users aware of the possibility

**Comment by maurizi** [comment]
I haven't seen this in a while.  Closing until it can be reproduced.
