### ISSUE TITLE
vagrant up fails with too many errors

### ISSUE THREAD

**Issue by COLABORATI** [OpenTreeMap/otm-vagrant#39]
Too many errors to paste here, please check the status of this project, thanks!

**Comment by maurizi** [comment]
Thanks @COLABORATI, fixes are in the works.  I have a PR open now but  it still needs a little work, I'll let you know when it's ready, should be soon.

**Comment by maurizi** [comment]
@COLABORATI Can you try again with the latest `master` branch of this project as well as the 3 child projects (`otm-core`, `otm-ecoservice`, and `otm-tiler`)?

I think all issues should be fixed now.
